AWSTemplateFormatVersion: 2010-09-09
Description: >
  Creates SSL certs, S3 buckets, and Cloudfront distributions for www and non-www domains.

Parameters:
  DomainName:
    Type: String
    Description: The domain name.
  HostedZoneId:
    Type: String
    Description: Hosted Zone Id of your domain name.
  
  PriceClass:
    Type: String
    Description: The CloudFront distribution price class
    Default: 'PriceClass_100'
    AllowedValues:
      - 'PriceClass_100'
      - 'PriceClass_200'
      - 'PriceClass_All'

Resources:
  Cert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          ValidationDomain: !Ref DomainName
      ValidationMethod: DNS
  
  WWWCert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub "www.${DomainName}"
      DomainValidationOptions:
        - DomainName: !Sub "www.${DomainName}"
          ValidationDomain: !Sub "www.${DomainName}"
      ValidationMethod: DNS
  
  WWWBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "www.${DomainName}"
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  WWWBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WWWBucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Resource: !Join ['', ['arn:aws:s3:::', !Ref WWWBucket, '/*']]
            Principal: '*'
  
  RedirectBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DomainName
      PublicAccessBlockConfiguration:
        BlockPublicPolicy: false
        RestrictPublicBuckets: false

      WebsiteConfiguration:
        RedirectAllRequestsTo:
            HostName: !Sub "www.${DomainName}"
            Protocol: https
  
  WWWCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub "www.${DomainName}"
        DefaultCacheBehavior:
          Compress: true
          ForwardedValues:
            QueryString: true
          TargetOriginId: www-s3-bucket
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        DefaultRootObject: index.html
        HttpVersion: http2
        CustomErrorResponses:
          - ErrorCachingMinTTL: 300
            ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCachingMinTTL: 300
            ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        Origins:
          - DomainName: !Join ['', [!Ref WWWBucket, '.s3.amazonaws.com']]
            Id: www-s3-bucket
            S3OriginConfig:
              OriginAccessIdentity:
                !Join ['', ['origin-access-identity/cloudfront/', !Ref WWWCloudFrontOriginAccessIdentity]]
        PriceClass: !Ref PriceClass
        ViewerCertificate:
          AcmCertificateArn: !Ref WWWCert
          MinimumProtocolVersion: TLSv1.2_2019
          SslSupportMethod: sni-only

  WWWCloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub 'CloudFront OAI for ${DomainName}'
  
  RedirectCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
        DefaultCacheBehavior:
          Compress: true
          ForwardedValues:
            QueryString: false
          TargetOriginId: !Join ['', [!Ref RedirectBucket, '.s3.amazonaws.com']]
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        DefaultRootObject: index.html
        HttpVersion: http2
        CustomErrorResponses:
          - ErrorCachingMinTTL: 300
            ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCachingMinTTL: 300
            ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        Origins:
          - DomainName: !Join ['', [!Ref RedirectBucket, '.s3.amazonaws.com']]
            Id: !Join ['', [!Ref RedirectBucket, '.s3.amazonaws.com']]
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
            
        PriceClass: !Ref PriceClass
        ViewerCertificate:
          AcmCertificateArn: !Ref Cert
          MinimumProtocolVersion: TLSv1.1_2016
          SslSupportMethod: sni-only

  RedirectCloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub 'CloudFront OAI for ${DomainName}'

  WWWDomain:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub "${DomainName}."
      Name: !Sub "www.${DomainName}"
      Type: CNAME
      TTL: 60
      ResourceRecords:
      - !GetAtt [WWWCloudFrontDistribution, DomainName]

  RedirectDomain:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Ref DomainName
      HostedZoneId: !Ref HostedZoneId
      Type: A
      AliasTarget: 
        DNSName: !GetAtt RedirectCloudFrontDistribution.DomainName
        # DO NOT CHANGE HostedZoneId = Some Magic AWS Thingy
        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html
        HostedZoneId: Z2FDTNDATAQYW2

Outputs:
  WWWCloudFrontDomain:
    Value: !GetAtt WWWCloudFrontDistribution.DomainName
  WWWDomain:
    Value: !Sub "www.${DomainName}"
  StackName:
    Value: !Ref AWS::StackName
  AccountId:
    Value: !Ref AWS::AccountId
  Region:
    Value: !Ref AWS::Region
  RedirectCloudFront: 
    Value: !Ref RedirectCloudFrontDistribution
    
# aws cloudformation create-stack --stack-name domain-web --template-body file://./web.yml --parameters \
# ParameterKey=DomainName,ParameterValue=YOUR_DOMAIN_NAME.com
# ParameterKey=HostedZoneId,ParameterValue=XXXXXXXXXXX